# -*- coding: utf-8 -*-
"""BD_project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlIf6hbz_wgZGmNZOQEBe0rshoW1ieef
"""

#Objetivo: montar um modelo capaz de predizer se a pessoa sobreviveu ou não ao Titanic de acordo com as outras variaveis classe social,	sexo,	idade, e	cabine.
#Aqui faremos uma análise dos dados, avaliar as variaveis que podem ou não interferir na predição do nosso modelo ou até as variaveis que são dispensáveis.
!pip install pandas
!pip install matplotlib
!pip install seaborn

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plott
import seaborn as sns

data_frame = pd.read_csv('/content/train.csv')
data_frame.info()

data_frame = data_frame.rename(columns={
    "Survived": "sobreviveu",
    "Pclass": "classe social", 
    "Name": "nome", 
    "Sex": "sexo", 
    "Age": "idade",
    "SibSp": "irmão", 
    "Parch": "pais", 
    "Ticket": "codigo", 
    "Fare": "tarifa", 
    "Cabin": "cabine", 
    "Embarked": "porto" 
})

data_frame.info()

lista = ["nome", "codigo", "porto", "cabine"]
for item in lista:
  data_frame = data_frame.drop(item, 1) #0 = dropar linha/1 = dropar coluna.
data_frame["sobreviveu"].mean()

data_frame.describe() #descreve alguns dados estatisticos

data_frame.corr()

parse_df = data_frame.corr(method='pearson')
plott.matshow(parse_df)

sns.heatmap(parse_df, annot=True)

tr = lambda i : print('\n'+i * 70,'\n')

#A partir dessa análise podemos observar que existe uma relação entre os sobreviventes/mortos e a classe social.
sobreviventes = data_frame.loc[data_frame["sobreviveu"] == 1]
print("Sobreviventes (total de 342):")
print("Classe alta: {}%".format((len(sobreviventes.loc[sobreviventes["classe social"] == 1]["classe social"])*100)/342))
print("Classe média: {}%".format((len(sobreviventes.loc[sobreviventes["classe social"] == 2]["classe social"])*100)/342))
print("Classe baixa: {}%".format((len(sobreviventes.loc[sobreviventes["classe social"] == 3]["classe social"])*100)/342))
print("---------------------------------")
print("Mortos (total de 549):")
mortos = data_frame.loc[data_frame["sobreviveu"] == 0]
print("Classe alta: {}%".format((len(mortos.loc[mortos["classe social"] == 1]["classe social"])*100)/549))
print("Classe média: {}%".format((len(mortos.loc[mortos["classe social"] == 2]["classe social"])*100)/549))
print("Classe baixa: {}%".format((len(mortos.loc[mortos["classe social"] == 3]["classe social"])*100)/549))

tr('=-')

classe_alta = data_frame.loc[data_frame['classe social'] == 1]
classe_media = data_frame.loc[data_frame['classe social'] == 2]
classe_baixa = data_frame.loc[data_frame['classe social'] == 3]
print("Classe alta (total de 216 pessoas): ")
print("Sobreviventes: %f" %((len(classe_alta.loc[classe_alta['sobreviveu'] == 1])*100)/216)+'%')
print("Mortos: %f" %((len(classe_alta.loc[classe_alta['sobreviveu'] == 0])*100)/216)+'%')
print("------------------------------------")
print("Classe media (total de 184 pessoas): ")
print("Sobreviventes: %f" %((len(classe_media.loc[classe_media['sobreviveu'] == 1])*100)/184)+'%')
print("Mortos: %f" %((len(classe_media.loc[classe_media['sobreviveu'] == 0])*100)/184)+'%')
print("------------------------------------")
print("Classe baixa (total de 491 pessoas): ")
print("Sobreviventes: %f" %((len(classe_baixa.loc[classe_baixa['sobreviveu'] == 1])*100)/491)+'%')
print("Mortos: %f" %((len(classe_baixa.loc[classe_baixa['sobreviveu'] == 0])*100)/491)+'%')

#A partir dessa análise podemos conclúir que a relação entre os sobreviventes/mortos e o sexo é forte.
print("Sobreviventes (total de 342):")
print("Homens: {}%".format((len(sobreviventes.loc[sobreviventes["sexo"] == "male"]["sexo"])*100)/342))
print("Mulheres: {}%".format((len(sobreviventes.loc[sobreviventes["sexo"] == "female"]["sexo"])*100)/342))
print("------------------------------")
print("Mortos (total de 549):")
print("Homens: {}%".format((len(mortos.loc[mortos["sexo"] == "male"]["sexo"])*100)/549))
print("Mulheres: {}%".format((len(mortos.loc[mortos["sexo"] == "female"]["sexo"])*100)/549))

tr('=-')

female = data_frame.loc[data_frame["sexo"] == 'female']
male = data_frame.loc[data_frame["sexo"] == 'male']
print("Mulheres (total de 314): ")
print("Sobreviveu: %f"%((len(female.loc[female['sobreviveu'] == 1])*100)/314)+'%')
print("Morreu: %f" %((len(female.loc[female['sobreviveu'] == 0])*100)/314)+'%')
print("-------------------------------")
print("Homens (total de 577): ")
print("Sobreviveu: %f"%((len(male.loc[male['sobreviveu'] == 1])*100)/577)+'%')
print("Morreu: %f" %((len(male.loc[male['sobreviveu'] == 0])*100)/577)+'%')

#data_frame["tarifa"].mean() #32,20 dolares.
#como existe um número muito grande de variaveis nessa coluna, utilizamos uma amostra de 200 para os maiores e menores preços de tarifas.
#a quantidade de 200 foi escolhida pois se enquadra dentro da média.
maiores_tarifas = data_frame.nlargest(200, "tarifa")
menores_tarifas = data_frame.nsmallest(215, "tarifa") #215 pois as 15 menores tarifas tem valores = 0.
menores_tarifas = menores_tarifas[menores_tarifas["tarifa"] != 0] #adicionando todos os valores diferentes de 0.

print("Tarifas com custo acima da média (amostra de 200 tarifas): ")
print("Sobreviventes: {}%".format((len(maiores_tarifas.loc[maiores_tarifas["sobreviveu"] == 1])*100)/200))
print("Mortos: {}%".format((len(maiores_tarifas.loc[maiores_tarifas["sobreviveu"] == 0])*100)/200))

print("-----------------------------------------------------------")

print("Tarifas com custo abaixo da média (amostra de 200 tarifas): ")
print("Sobreviventes: {}%".format((len(menores_tarifas.loc[menores_tarifas["sobreviveu"] == 1])*100)/200))
print("Mortos: {}%".format((len(menores_tarifas.loc[menores_tarifas["sobreviveu"] == 0])*100)/200))

#dividimos o dataframe em 3 datasets distintos e contabilizamos em quantidades iguais, aproximadamente 233 pessoas em cada dataset.
#177 pessoas não tiveram suas idades divulgadas então analisamos somente as 714.
#data_frame.loc[data_frame["idade"].isnull() == True]
#média de 29 anos e 7 meses.
ate_22 = data_frame.loc[data_frame['idade'] <= 22] #até os 22 anos.
ate_33 = data_frame.loc[data_frame['idade'] > 22] 
ate_33 = ate_33.loc[ate_33['idade'] <= 33] #dos 23 aos 33 anos.
mais_33 = data_frame.loc[data_frame['idade'] > 33] #mais de 34 anos.

print("Sobreviventes (total de 290 com idades não nulas)")
print("Até 22 anos: {}%".format((len(ate_22.loc[ate_22['sobreviveu'] == 1])*100)/290)) 
print("Dos 23 aos 33: {}%".format((len(ate_33.loc[ate_33['sobreviveu'] == 1])*100)/290))
print("Mais de 34 anos: {}%".format((len(mais_33.loc[mais_33['sobreviveu'] == 1])*100)/290))
print("---------------------------------------------------")
print("Mortos (total de 424 com idades não nulas): ")
print("Até 22 anos: {}%".format((len(ate_22.loc[ate_22['sobreviveu'] == 0])*100)/424))
print("Dos 23 aos 33 anos: {}%".format((len(ate_33.loc[ate_33['sobreviveu'] == 0])*100)/424))
print("Mais de 34 anos: {}%".format((len(mais_33.loc[mais_33['sobreviveu'] == 0])*100)/424))

tr('=-')

print("Até 22 anos (total de 231 pessoas): ")
print("Sobreviventes: {}%".format((len(ate_22.loc[ate_22['sobreviveu'] == 1])*100)/231)) 
print("Mortos: {}%".format((len(ate_22.loc[ate_22['sobreviveu'] == 0])*100)/231))
print("---------------------------------------------------")
print("Dos 23 aos 33 anos (total de 232 pessoas): ")
print("Sobreviventes: {}%".format((len(ate_33.loc[ate_33['sobreviveu'] == 1])*100)/232))
print("Mortos: {}%".format((len(ate_33.loc[ate_33['sobreviveu'] == 0])*100)/232))
print("---------------------------------------------------")
print("Mais de 34 anos (total de 251 pessoas): ")
print("Sobreviventes: {}%".format((len(mais_33.loc[mais_33['sobreviveu'] == 1])*100)/251))
print("Mortos: {}%".format((len(mais_33.loc[mais_33['sobreviveu'] == 0])*100)/251))

#atravéz da interpretação dos dados, podemos concluir que o fator de existência de irmãos a bordo não influênciou na sobrevivência dessas pessoas. 
irmaos = data_frame.loc[data_frame['irmão'] != 0]
sem_irmaos = data_frame.loc[data_frame['irmão'] == 0]

print("Sobreviventes (total de 342 pessoas): ")
print("Com 1 irmão ou mais: {}%".format((len(irmaos.loc[irmaos['sobreviveu'] == 1])*100)/342))
print("Sem irmãos a bordo: {}".format((len(sem_irmaos.loc[sem_irmaos['sobreviveu'] == 1])*100)/342))
print('-------------------------------------------------')
print("Mortos (total de 549 pessoas): ")
print("Com 1 irmão ou mais: {}%".format((len(irmaos.loc[irmaos['sobreviveu'] == 0])*100)/549))
print("Sem irmãos a bordo: {}".format((len(sem_irmaos.loc[sem_irmaos['sobreviveu'] == 0])*100)/549))

tr('=-')

print("Com 1 irmão ou mais a bordo (total de 283 pessoas): ")
print("Sobreviventes: {}%".format((len(irmaos.loc[irmaos['sobreviveu'] == 1])*100)/283))
print("Mortos: {}%".format((len(irmaos.loc[irmaos['sobreviveu'] == 0])*100)/283))
print('-------------------------------------------------')
print("Sem irmãos a bordo (total de 608 pessoas): ")
print("Sobreviventes: {}%".format((len(sem_irmaos.loc[sem_irmaos['sobreviveu'] == 1])*100)/608))
print("Mortos: {}%".format((len(sem_irmaos.loc[sem_irmaos['sobreviveu'] == 0])*100)/608))

print("Sobreviventes (total de 342): ")
print("Pais a bordo: %f" %((len(sobreviventes.loc[sobreviventes['pais'] != 0])*100)/342)+'%')
print("Sem pais a bordo: %f" %((len(sobreviventes.loc[sobreviventes['pais'] == 0])*100)/342)+'%')
print('------------------------------')
print("Mortos (total de 549): ")
print("Pais a bordo: %f" %((len(mortos.loc[mortos['pais'] != 0])*100)/549)+'%')
print("Sem pais a bordo: %f" %((len(mortos.loc[mortos['pais'] == 0])*100)/549)+'%')

tr('=-')

possui_pais = data_frame.loc[data_frame['pais'] != 0]
sem_pais = data_frame.loc[data_frame['pais'] == 0]
print("Possui pais a bordo (total de 213 pessoas):")
print("Sobreviventes: %f" %((len(possui_pais.loc[possui_pais['sobreviveu'] == 1])*100)/213)+'%')
print("Mortos: %f" %((len(possui_pais.loc[possui_pais['sobreviveu'] == 0])*100)/213)+'%')
print('------------------------------------------')
print("Sem pais a bordo (total de 678 pessoas):")
print("Sobreviventes: %f" %((len(sem_pais.loc[sem_pais['sobreviveu'] == 1])*100)/678)+'%')
print("Mortos: %f" %((len(sem_pais.loc[sem_pais['sobreviveu'] == 0])*100)/678)+'%')